name: self_utils
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.3 #连接
  bot_toast: ^4.0.3 #弹窗
  permission_handler: ^10.0.0 #权限
  get: ^4.6.5 #getx状态管理
  path_provider: ^2.0.1
  package_info: ^2.0.2 #包信息
  sentry: ^5.0.0  #日志监听
  image_gallery_saver: ^1.7.1 #文件保存
#  ios_share:
#    git:
#      url: https://github.com/NayoLx/ios_share.git
  encrypt: ^5.0.1 #加密解锁
  intl: ^0.17.0 #本地化和国际化
  flutter_image_compress: ^1.1.0 #图片压缩
  dio: ^4.0.0  #接口请求
  mqtt_client: ^9.3.1 #mqtt
  cookie_jar: ^3.0.1 #cookie
  dio_cookie_manager: ^2.0.0
  shared_preferences: ^2.0.5 #key-value存储
  tabbed_view: ^1.1.0+1 #tab组件
  multi_split_view: ^1.5.0 #doking
  video_player: ^2.3.0 #视频播放
  orientation: ^1.1.0
#  sensors_plus: ^1.3.4+1 #陀螺仪
  photo_view: ^0.14.0 #图片查看
  keyboard_actions: ^4.0.1 #键盘
  back_button_interceptor: ^6.0.1 #键盘管理
  simple_animations: ^5.0.0+2
  provider: ^6.0.1 #状态管理
#  flutter_shortcuts: ^1.2.2 #app图标长按按钮
  expandable: ^5.0.1
  quick_actions: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
